/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author bryan
 */
public class Interfaz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        btn7 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btndecimal = new javax.swing.JButton();
        btnigual = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        btnNegativo = new javax.swing.JButton();
        btnBorrarPantalla = new javax.swing.JButton();
        btnBorrarDigito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 33, 391, 63));

        btn7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(this::btn7ActionPerformed);
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 215, 86, 51));

        btn0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn0.setText("0");
        jPanel1.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 422, 86, 51));

        btnResta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnResta.setText("-");
        jPanel1.add(btnResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 353, 86, 51));

        btn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn1.setText("1");
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 353, 86, 51));

        btn4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(this::btn4ActionPerformed);
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 284, 86, 51));

        btn5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(this::btn5ActionPerformed);
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 284, 86, 51));

        btnDividir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDividir.setText("/");
        btnDividir.addActionListener(this::btnDividirActionPerformed);
        jPanel1.add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 215, 86, 51));

        btn9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(this::btn9ActionPerformed);
        jPanel1.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 215, 86, 51));

        btn8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn8.setText("8");
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 215, 86, 51));

        btn2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn2.setText("2");
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 353, 86, 51));

        btn3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn3.setText("3");
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 353, 86, 51));

        btnMultiplicar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMultiplicar.setText("*");
        jPanel1.add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 284, 86, 51));

        btn6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(this::btn6ActionPerformed);
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 284, 86, 51));

        btndecimal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btndecimal.setText(",");
        jPanel1.add(btndecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 422, 86, 51));

        btnigual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnigual.setText("=");
        jPanel1.add(btnigual, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 422, 86, 51));

        btnSuma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSuma.setText("+");
        jPanel1.add(btnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 422, 86, 51));

        btnReiniciar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReiniciar.setText("AC");
        btnReiniciar.addActionListener(this::btnReiniciarActionPerformed);
        jPanel1.add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 131, 86, 51));

        btnNegativo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNegativo.setText("-");
        btnNegativo.addActionListener(this::btnNegativoActionPerformed);
        jPanel1.add(btnNegativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 131, 86, 51));

        btnBorrarPantalla.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBorrarPantalla.setText("CE");
        btnBorrarPantalla.addActionListener(this::btnBorrarPantallaActionPerformed);
        jPanel1.add(btnBorrarPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 131, 86, 51));

        btnBorrarDigito.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBorrarDigito.setText("<-");
        btnBorrarDigito.addActionListener(this::btnBorrarDigitoActionPerformed);
        jPanel1.add(btnBorrarDigito, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 131, 86, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn6ActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnNegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNegativoActionPerformed

    private void btnBorrarPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarPantallaActionPerformed

    private void btnBorrarDigitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarDigitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarDigitoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBorrarDigito;
    private javax.swing.JButton btnBorrarPantalla;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnNegativo;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton btndecimal;
    private javax.swing.JButton btnigual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
